const files=[
'historia/capitulo-01-el-eco-en-la-madera.md','historia/capitulo-02-el-teorema-del-naranjo.md','historia/capitulo-03-la-moneda-y-el-sillon.md','historia/capitulo-04-la-grieta-de-septiembre.md','historia/capitulo-05-el-asado-del-2000.md','historia/capitulo-06-el-canal-del-2001.md','historia/capitulo-07-las-cicatrices-del-2002.md','historia/capitulo-08-el-mostrador-y-el-canal-digital.md'];
const visuals={5:[{src:'assets/story/2001-restaurante-chino.webp',alt:'José y Paz conversando en un restaurante chino, Santiago, 2001',caption:'Santiago · 2001'}]};
const book=document.querySelector('#book'), agenda=document.querySelector('#agenda'), open=document.querySelector('#openAgenda'), prev=document.querySelector('#prev'), next=document.querySelector('#next'), label=document.querySelector('#pageLabel');
let pages=[], current=0;
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mdToHtml(md){let lines=md.replace(/\r/g,'').split('\n'),out=[],title='',date='';for(let i=0;i<lines.length;i++){let l=lines[i].trim();if(!l)continue;if(l.startsWith('## Nota editorial'))break;if(/^# /.test(l)){title=l.slice(2);continue}if(/^\*\*[^*]+\*\*$/.test(l)){date=l.replace(/\*\*/g,'');continue}if(l==='---')continue;if(/^> /.test(l)){out.push(`<blockquote>${esc(l.slice(2))}</blockquote>`);continue}if(/^### /.test(l)){out.push(`<h3>${esc(l.slice(4))}</h3>`);continue}if(/^## /.test(l)){out.push(`<h2>${esc(l.slice(3))}</h2>`);continue}if(/^[-•]/.test(l)||/^\*[^*]+\*$/.test(l))continue;out.push(`<p>${esc(l)}</p>`)}return{title,date,body:out.join('')}}
function visualHtml(i){return(visuals[i]||[]).map(v=>`<figure class="story-photo"><img src="${v.src}" alt="${esc(v.alt)}" loading="lazy"><figcaption>${esc(v.caption)}</figcaption></figure>`).join('')}
async function load(){for(const f of files){try{const r=await fetch(f);const t=await r.text();pages.push(mdToHtml(t))}catch(e){console.error(e)}}render()}
function render(){book.innerHTML=pages.map((p,i)=>`<article class="page text-page" data-page="${i}"><div class="page-no">${String(i+1).padStart(2,'0')}</div><p class="hand-note">${esc(p.date||'ARCHIVO DE MEMORIA')}</p>${p.title?`<h2>${esc(p.title)}</h2>`:''}${visualHtml(i)}<div class="story">${p.body}</div></article>`).join('');update()}
function update(){document.querySelectorAll('.page').forEach((p,i)=>p.classList.toggle('active',i===current));label.textContent=`HOJA ${String(current+1).padStart(2,'0')} / ${String(pages.length).padStart(2,'0')}`;prev.disabled=current===0;next.disabled=current>=pages.length-1;window.scrollTo({top:agenda.offsetTop,behavior:'smooth'})}
open.onclick=()=>{agenda.setAttribute('aria-hidden','false');agenda.classList.add('open');open.disabled=true;if(!pages.length)load()};prev.onclick=()=>{if(current>0){current--;update()}};next.onclick=()=>{if(current<pages.length-1){current++;update()}};