import { buildPlanBBlueprint, createPlanBReaderSession, directorPlanB, buildPlanBOutcome } from '../plan-b/agents/plan-b-network.js';
const db=window.supabase.createClient('https://bqrwcmrpzvtjoebmqiji.supabase.co','sb_publishable_XK4dh9Ch_7MebSMO7JJm7Q_8CXu2Qa8'); const $=id=>document.getElementById(id); const slug=new URLSearchParams(location.search).get('slug'); let story=null,session=null;
const put=(id,value)=>$(id).textContent=value??''; function fail(message){$('readerState').textContent=message;$('readerState').className='reader-state error';}
function renderStory(){
  $('readerState').hidden=true;$('story').hidden=false;put('storyGenre',`${story.genre||'Historia'} · ${story.modules?.planB?'Plan B disponible':'lectura abierta'}`);put('storyTitle',story.title);put('storyByline',`Por ${story.author_name}`);put('storySynopsis',story.synopsis);
  const chars=$('characters');chars.replaceChildren();(story.characters||[]).forEach(c=>{const card=document.createElement('article');card.className='character';const h=document.createElement('h3');h.textContent=c.name;const p=document.createElement('p');p.textContent=c.description;card.append(h,p);chars.append(card)});
  const pages=$('pages');pages.replaceChildren();(story.pages||[]).forEach(p=>{const article=document.createElement('article');article.className='page';const n=document.createElement('span');n.className='page-number';n.textContent=String(p.position).padStart(2,'0');const h=document.createElement('h2');h.textContent=p.title;const body=document.createElement('p');body.textContent=p.body;article.append(n,h,body);pages.append(article)});
  if(story.modules?.planB&&story.plan_b_blueprint?.branches?.length){$('planB').hidden=false;put('planBIntro','En cada momento aparece una pregunta y tres alternativas. Elige una; la historia responde y continúa.');const blueprint=story.plan_b_blueprint.interaction==='one-question-three-choices'?story.plan_b_blueprint:buildPlanBBlueprint({title:story.title,sections:story.pages.map(page=>page.body),protagonist:story.characters[0]?.name||'el protagonista'});session=createPlanBReaderSession(blueprint);renderPlanB();}
}
function renderPlanB(){
  const stage=$('planBStage');stage.replaceChildren();
  if(session.status==='completed'){const outcome=buildPlanBOutcome(session);const box=document.createElement('div');box.className='outcome';const h=document.createElement('h3');h.textContent='Tu trayectoria';box.append(h);outcome.sections.forEach(s=>{const p=document.createElement('p');p.textContent=s.text;box.append(p)});const end=document.createElement('p');end.textContent=outcome.epilogue;box.append(end);stage.append(box);return;}
  const branch=session.blueprint.branches[session.current];const context=document.createElement('div');context.className='branch-context';context.textContent=branch.context;const question=document.createElement('h3');question.className='plan-question';question.textContent=branch.question.text;const list=document.createElement('div');list.className='question-list';branch.question.choices.forEach(choice=>{const b=document.createElement('button');b.className='question';b.textContent=choice.text;b.onclick=()=>choose(branch,choice);list.append(b)});stage.append(context,question,list);
  if(session.actions.length){const history=document.createElement('div');session.actions.forEach(item=>{const itemEl=document.createElement('div');itemEl.className='action';itemEl.textContent=item.bridge;history.append(itemEl)});stage.append(history)}
}
function choose(branch,choice){try{session=directorPlanB(session,{branchId:branch.id,questionId:branch.question.id,choiceId:choice.id});const stage=$('planBStage');stage.replaceChildren();const response=document.createElement('div');response.className='action';const label=document.createElement('p');label.className='eyebrow';label.textContent='LA HISTORIA RESPONDE';const narrative=document.createElement('p');narrative.textContent=session.actions.at(-1).bridge;const action=document.createElement('p');action.textContent=session.actions.at(-1).action;const next=document.createElement('button');next.className='question continue-plan-b';next.textContent=session.status==='completed'?'DESCUBRIR MI DESENLACE →':'SEGUIR LEYENDO →';next.onclick=renderPlanB;response.append(label,narrative,action,next);stage.append(response)}catch(error){const e=document.createElement('p');e.className='error';e.textContent=error.message;$('planBStage').append(e)}}
async function load(){
  if(!slug)return fail('Esta obra necesita un enlace completo.');const {data,error}=await db.from('user_stories').select('id,slug,title,author_name,synopsis,genre,modules,plan_b_blueprint').eq('slug',slug).eq('status','published').eq('visibility','public').not('published_at','is',null).single();if(error||!data)return fail('La obra no existe o todavía no está publicada.');story=data;const [pages,characters]=await Promise.all([db.from('user_story_pages').select('position,title,body').eq('story_id',story.id).order('position'),db.from('user_story_characters').select('name,description,role,relationship,position').eq('story_id',story.id).order('position')]);if(pages.error||characters.error)return fail('No se pudo cargar el contenido de la obra.');story.pages=pages.data||[];story.characters=characters.data||[];renderStory();
}load();
