import { buildPlanBBlueprint, createPlanBReaderSession, directorPlanB, buildPlanBOutcome } from '../plan-b/agents/plan-b-network.js';
const db=window.supabase.createClient('https://bqrwcmrpzvtjoebmqiji.supabase.co','sb_publishable_XK4dh9Ch_7MebSMO7JJm7Q_8CXu2Qa8'); const $=id=>document.getElementById(id); const slug=new URLSearchParams(location.search).get('slug'); let story=null,session=null;
const put=(id,value)=>$(id).textContent=value??''; function fail(message){$('readerState').textContent=message;$('readerState').className='reader-state error';}
function compactPages(source){const words=(source||[]).flatMap(page=>String(page.body||'').split(/\s+/).filter(Boolean));if(!words.length)return[];const groups=[];for(let index=0;index<words.length;index+=300)groups.push(words.slice(index,index+300));if(groups.length>1&&groups.at(-1).length<200){const combined=[...groups.at(-2),...groups.at(-1)];const splitAt=combined.length<=450?combined.length:Math.ceil(combined.length/2);groups.splice(-2,2,combined.slice(0,splitAt),...(splitAt<combined.length?[combined.slice(splitAt)]:[]))}return groups.map((group,index)=>({position:index+1,title:index===0?story.title:`Página ${index+1}`,body:group.join(' ')}))}
async function signed(path){if(!path)return null;const {data}=await db.storage.from('story-media').createSignedUrl(path,3600);return data?.signedUrl||null}
function renderStory(){
  $('readerState').hidden=true;$('story').hidden=false;put('storyGenre',`${story.genre||'Historia'} · ${story.modules?.planB?'Plan B disponible':'lectura abierta'}`);put('storyTitle',story.title);put('storyByline',`Por ${story.author_name}`);put('storySynopsis',story.synopsis);
  if(story.coverUrl){$('storyCover').hidden=false;$('coverImage').src=story.coverUrl;$('coverImage').alt=`Portada de ${story.title}`;put('coverTitle',story.title);put('coverAuthor',story.author_name)}
  const pages=$('pages');pages.replaceChildren();(story.pages||[]).forEach(p=>{const article=document.createElement('article');article.className='page';const n=document.createElement('span');n.className='page-number';n.textContent=String(p.position).padStart(2,'0');const h=document.createElement('h2');h.textContent=p.title;const body=document.createElement('p');body.textContent=p.body;article.append(n,h,body);pages.append(article)});
  if(story.album?.length){$('album').hidden=false;const grid=$('albumGrid');grid.replaceChildren();story.album.forEach((item,index)=>{const image=new Image();image.src=item.url;image.alt=item.alt_text||`Escena ${index+1} de ${story.title}`;grid.appendChild(image)})}
  const characterGrid=$('characterGrid');characterGrid.replaceChildren();(story.characters||[]).forEach(character=>{const card=document.createElement('article');card.className='character';if(character.portraitUrl){const portrait=new Image();portrait.className='character-portrait';portrait.src=character.portraitUrl;portrait.alt=`Retrato de ${character.name}`;card.appendChild(portrait)}const role=document.createElement('span');role.className='character-role';role.textContent=character.role==='protagonist'?'PROTAGONISTA':character.role==='coprotagonist'?'COPROTAGONISTA':'PERSONAJE';const name=document.createElement('h3');name.textContent=character.name;const description=document.createElement('p');description.textContent=character.description;card.append(role,name,description);if(character.relationship){const relation=document.createElement('small');relation.textContent=character.relationship;card.appendChild(relation)}characterGrid.appendChild(card)});$('characters').hidden=!story.characters?.length;
  if(story.modules?.planB&&story.plan_b_blueprint?.branches?.length){$('planB').hidden=false;put('planBIntro','Elige una alternativa. La historia se escribirá al final.');const blueprint=story.plan_b_blueprint.interaction==='one-question-two-choices'?story.plan_b_blueprint:buildPlanBBlueprint({title:story.title,sections:story.pages.map(page=>page.body),protagonist:story.characters[0]?.name||'el protagonista'});session=createPlanBReaderSession(blueprint);renderPlanB();}
}
function renderPlanB(){
  const stage=$('planBStage');stage.replaceChildren();
  if(session.status==='completed'){const outcome=buildPlanBOutcome(session);const box=document.createElement('div');box.className='outcome';const h=document.createElement('h3');h.textContent='La historia que construiste';box.append(h);outcome.sections.forEach(s=>{const section=document.createElement('section');const title=document.createElement('h4');title.textContent=s.title;const p=document.createElement('p');p.textContent=s.text;section.append(title,p);box.append(section)});const end=document.createElement('p');end.textContent=outcome.epilogue;box.append(end);stage.append(box);return;}
  const branch=session.blueprint.branches[session.current];const progress=document.createElement('p');progress.className='eyebrow';progress.textContent=`DECISIÓN ${branch.position} DE ${session.blueprint.branches.length}`;const question=document.createElement('h3');question.className='plan-question';question.textContent=branch.question.text;const list=document.createElement('div');list.className='question-list';branch.question.choices.forEach(choice=>{const b=document.createElement('button');b.className='question';b.textContent=choice.text;b.onclick=()=>choose(branch,choice);list.append(b)});stage.append(progress,question,list);
}
function choose(branch,choice){try{session=directorPlanB(session,{branchId:branch.id,questionId:branch.question.id,choiceId:choice.id});renderPlanB();$('planBStage').scrollIntoView({behavior:'smooth',block:'start'})}catch(error){const e=document.createElement('p');e.className='error';e.textContent=error.message;$('planBStage').append(e)}}
async function load(){
  if(!slug)return fail('Esta obra necesita un enlace completo.');const {data,error}=await db.from('user_stories').select('id,slug,title,author_name,synopsis,genre,modules,plan_b_blueprint,cover_storage_path').eq('slug',slug).eq('status','published').eq('visibility','public').not('published_at','is',null).single();if(error||!data)return fail('La obra no existe o todavía no está publicada.');story=data;const [pages,characters,media]=await Promise.all([db.from('user_story_pages').select('position,title,body').eq('story_id',story.id).order('position'),db.from('user_story_characters').select('name,description,role,relationship,position,portrait_storage_path,portrait_status').eq('story_id',story.id).order('position'),db.from('user_story_media').select('storage_path,position,media_role,alt_text').eq('story_id',story.id).eq('status','ready').is('deleted_at',null).order('position')]);if(pages.error||characters.error||media.error)return fail('No se pudo cargar el contenido de la obra.');story.pages=compactPages(pages.data||[]);story.coverUrl=await signed(story.cover_storage_path||media.data?.find(item=>item.media_role==='cover')?.storage_path);story.characters=await Promise.all((characters.data||[]).map(async item=>({...item,portraitUrl:item.portrait_status==='ready'?await signed(item.portrait_storage_path):null})));story.album=(await Promise.all((media.data||[]).filter(item=>item.media_role==='album').map(async item=>({...item,url:await signed(item.storage_path)})))).filter(item=>item.url);renderStory();
}load();
