const URL='https://bqrwcmrpzvtjoebmqiji.supabase.co';
const KEY='sb_publishable_XK4dh9Ch_7MebSMO7JJm7Q_8CXu2Qa8';
const db=window.supabase.createClient(URL,KEY); const $=id=>document.getElementById(id);
const REDIRECT_URL=new URL('./',location.href).href; const LIMIT=650*1024;
let user=null,stories=[],active=null,characters=[],media=[];

function notice(text,error=false){const box=$('message');box.hidden=!text;box.textContent=text||'';box.style.background=error?'#fff0f1':'#edf7f1';box.style.color=error?'#7d2433':'#235d42'}
function ext(file){return (file.name.split('.').pop()||'webp').toLowerCase()}
async function compress(file){if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error('Usa una imagen JPG, PNG o WebP.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.84,blob;do{blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));quality-=.07}while(blob?.size>LIMIT&&quality>.4);if(!blob||blob.size>LIMIT)throw new Error('No fue posible reducir la imagen a 650 KB.');return new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.webp`,{type:'image/webp'})}
async function signed(path){if(!path)return null;const {data}=await db.storage.from('story-media').createSignedUrl(path,3600);return data?.signedUrl||null}
function fileCard({kind,title,detail,path,onFile,cover=false}){const card=document.createElement('article');card.className=`asset${cover?' cover':''}`;const preview=document.createElement('div');preview.className='preview';preview.textContent=path?'Cargando…':'Pendiente';if(path)signed(path).then(url=>{if(url){const img=new Image();img.src=url;img.alt=title;preview.replaceChildren(img)}else preview.textContent='Archivo guardado'});const name=document.createElement('strong');name.textContent=title;const copy=document.createElement('small');copy.textContent=detail;const label=document.createElement('label');label.className='button file-button';label.textContent=path?'REEMPLAZAR':'CARGAR IMAGEN';const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.onchange=async()=>{if(!input.files[0])return;label.textContent='GUARDANDO…';input.disabled=true;try{await onFile(input.files[0]);notice(`${title}: imagen guardada.`);await loadOrder()}catch(error){notice(error.message,true);label.textContent=path?'REEMPLAZAR':'CARGAR IMAGEN';input.disabled=false}};label.appendChild(input);card.append(preview,name,copy,label);return card}
async function upload(file,folder){const ready=await compress(file);const path=`${user.id}/${active.id}/${folder}/${crypto.randomUUID()}.${ext(ready)}`;const {error}=await db.storage.from('story-media').upload(path,ready,{contentType:ready.type});if(error)throw error;return{file:ready,path}}
async function saveMedia(role,position,file){const previous=media.find(item=>item.media_role===role&&item.position===position);const saved=await upload(file,role);let error;if(previous){({error}=await db.from('user_story_media').update({storage_path:saved.path,file_name:saved.file.name,mime_type:saved.file.type,byte_size:saved.file.size,status:'ready',deleted_at:null}).eq('id',previous.id));if(!error&&previous.storage_path)await db.storage.from('story-media').remove([previous.storage_path])}else{({error}=await db.from('user_story_media').insert({story_id:active.id,owner_id:user.id,storage_path:saved.path,position,file_name:saved.file.name,mime_type:saved.file.type,byte_size:saved.file.size,status:'ready',media_role:role,caption:role==='cover'?'Portada de la obra':`Escena ${position} del álbum`,alt_text:role==='cover'?`Portada de ${active.title}`:`Escena ${position} de ${active.title}`,consent_confirmed_at:new Date().toISOString()}))}if(error){await db.storage.from('story-media').remove([saved.path]);throw error}if(role==='cover'){const {error:storyError}=await db.from('user_stories').update({cover_storage_path:saved.path,visual_status:'pending'}).eq('id',active.id);if(storyError)throw storyError}}
async function saveCharacter(character,file){const saved=await upload(file,`characters/${character.id}`);const old=character.portrait_storage_path;const source=character.portrait_source==='ai'?'ai':'upload';const {error}=await db.from('user_story_characters').update({portrait_source:source,portrait_storage_path:saved.path,portrait_status:'ready'}).eq('id',character.id);if(error){await db.storage.from('story-media').remove([saved.path]);throw error}if(old)await db.storage.from('story-media').remove([old])}
function requirements(){const needsCover=active.cover_config?.source==='ai';const coverReady=!needsCover||Boolean(active.cover_storage_path||media.some(m=>m.media_role==='cover'));const pendingCharacters=characters.filter(c=>c.portrait_source==='ai'&&c.portrait_status!=='ready').length;const albumReady=!active.modules?.album||media.filter(m=>m.media_role==='album'&&m.status==='ready').length>=4;return{coverReady,pendingCharacters,albumReady,ready:coverReady&&!pendingCharacters&&albumReady}}
function render(){const box=$('order');box.replaceChildren();if(!active)return;const head=document.createElement('header');head.className='order-head';head.innerHTML=`<div><h3>${active.title}</h3><p>Por ${active.author_name} · ${active.status==='published'?'publicada':'borrador'}</p></div><span class="badge">${active.visual_status==='ready'?'VISUAL COMPLETO':'PRODUCCIÓN PENDIENTE'}</span>`;box.appendChild(head);
  const coverSection=document.createElement('section');coverSection.className='asset-section';coverSection.innerHTML='<h4>Portada</h4><p>Imagen vertical limpia. El título y el autor se incorporan automáticamente al mostrar la obra.</p>';const coverGrid=document.createElement('div');coverGrid.className='asset-grid';const coverPath=active.cover_storage_path||media.find(m=>m.media_role==='cover')?.storage_path;coverGrid.appendChild(fileCard({kind:'cover',title:'Portada final',detail:coverPath?'Lista para publicación':'Obligatoria',path:coverPath,cover:true,onFile:file=>saveMedia('cover',1,file)}));coverSection.appendChild(coverGrid);box.appendChild(coverSection);
  if(characters.length){const section=document.createElement('section');section.className='asset-section';section.innerHTML='<h4>Personajes</h4><p>Un único retrato por personaje solicitado a Gen.</p>';const grid=document.createElement('div');grid.className='asset-grid';characters.forEach(character=>grid.appendChild(fileCard({kind:'character',title:character.name,detail:character.portrait_status==='ready'?'Retrato listo':character.portrait_source==='ai'?'Solicitado a Gen':'Imagen opcional',path:character.portrait_storage_path,onFile:file=>saveCharacter(character,file)})));section.appendChild(grid);box.appendChild(section)}
  if(active.modules?.album){const section=document.createElement('section');section.className='asset-section';section.innerHTML='<h4>Álbum visual</h4><p>Las cuatro escenas más significativas, respetando la continuidad de los personajes.</p>';const grid=document.createElement('div');grid.className='asset-grid';for(let position=1;position<=4;position++){const item=media.find(m=>m.media_role==='album'&&m.position===position);grid.appendChild(fileCard({kind:'album',title:`Escena ${position}`,detail:item?'Imagen lista':'Pendiente',path:item?.storage_path,onFile:file=>saveMedia('album',position,file)}))}section.appendChild(grid);box.appendChild(section)}
  const state=requirements();const complete=document.createElement('footer');complete.className='complete';complete.innerHTML=`<p>${state.ready?'Todos los recursos obligatorios están cargados.':'Falta completar: '+[!state.coverReady?'portada':'',state.pendingCharacters?`${state.pendingCharacters} personaje(s)`: '',!state.albumReady?'álbum':''].filter(Boolean).join(', ')+'.'}</p>`;const button=document.createElement('button');button.textContent=active.visual_status==='ready'?'PRODUCCIÓN COMPLETA ✓':'COMPLETAR PRODUCCIÓN';button.disabled=!state.ready||active.visual_status==='ready';button.onclick=completeOrder;complete.appendChild(button);box.appendChild(complete)}
async function completeOrder(){const state=requirements();if(!state.ready)return;const {error}=await db.from('user_stories').update({visual_status:'ready',visual_completed_at:new Date().toISOString()}).eq('id',active.id);if(error)return notice(error.message,true);notice('Producción visual completada. La obra ya utiliza estos recursos.');await loadStories(active.id)}
async function loadOrder(){if(!active)return;const [chars,assets,fresh]=await Promise.all([db.from('user_story_characters').select('id,name,position,portrait_source,portrait_status,portrait_storage_path').eq('story_id',active.id).order('position'),db.from('user_story_media').select('id,storage_path,position,status,media_role').eq('story_id',active.id).is('deleted_at',null).order('position'),db.from('user_stories').select('id,title,author_name,status,modules,cover_config,cover_storage_path,visual_status').eq('id',active.id).single()]);if(chars.error||assets.error||fresh.error)throw(chars.error||assets.error||fresh.error);characters=chars.data||[];media=assets.data||[];active={...active,...fresh.data};render()}
async function loadStories(preferred){const {data,error}=await db.from('user_stories').select('id,title,author_name,status,modules,cover_config,cover_storage_path,visual_status').order('updated_at',{ascending:false});if(error)throw error;stories=data||[];const select=$('storySelect');select.replaceChildren();stories.forEach(story=>{const option=document.createElement('option');option.value=story.id;option.textContent=`${story.visual_status==='ready'?'✓':'●'} ${story.title} · ${story.status==='published'?'PUBLICADA':'BORRADOR'}`;select.appendChild(option)});active=stories.find(s=>s.id===(preferred||active?.id))||stories[0]||null;$('workspace').hidden=!active;if(active){select.value=active.id;await loadOrder()}else notice('No hay obras asociadas a esta cuenta.')}
function renderAuth(){const signed=Boolean(user);$('authForm').hidden=signed;$('logoutBtn').hidden=!signed;$('authStatus').textContent=signed?`Sesión activa: ${user.email}`:'Ingresa con el correo propietario de las obras.';$('workspace').hidden=!signed||!active}
$('storySelect').onchange=async event=>{active=stories.find(s=>s.id===event.target.value);try{await loadOrder()}catch(error){notice(error.message,true)}};
$('loginBtn').onclick=async()=>{const email=$('email').value.trim();if(!email)return notice('Ingresa tu correo.',true);$('loginBtn').disabled=true;const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:REDIRECT_URL}});if(error){$('loginBtn').disabled=false;return notice(error.message,true)}notice(`Enlace enviado a ${email}. Revisa también Spam.`)};
$('logoutBtn').onclick=()=>db.auth.signOut();
db.auth.getSession().then(async({data})=>{user=data.session?.user||null;renderAuth();if(user)try{await loadStories()}catch(error){notice(error.message,true)}});db.auth.onAuthStateChange(async(event,session)=>{user=session?.user||null;renderAuth();if(user&&event==='SIGNED_IN')try{await loadStories()}catch(error){notice(error.message,true)}});
