import { PLAN_B_LIMITS, createPlanBReaderSession, directorPlanB, buildPlanBOutcome } from './agents/plan-b-network.js';
const $=id=>document.getElementById(id); const STORAGE_KEY='el_lado_b_reader_prototype_v2';
const choices=(id,texts)=>texts.map((text,index)=>({id:`${id}-${String.fromCharCode(97+index)}`,text,action:text.replace(/[.!?]+$/,'').toLowerCase(),bridge:`La elección ${index+1} abre una trayectoria distinta y conserva esta decisión en la memoria de la historia.`}));
const rows=[['La primera mirada','En el gimnasio de 1998, José descubre que mirar a Paz ya no se parece del todo a mirar a una amiga.','¿Qué decide hacer José cuando reconoce que está sintiendo algo distinto?'],['El naranjo','En la fiesta, Paz pregunta quién es Nadia. La pregunta parece pequeña, pero permite que los celos entren por primera vez en el lenguaje secreto de ambos.','¿Cómo responde José a la pregunta de Paz?'],['La moneda y el sillón','Una invitación aparentemente sencilla modifica el límite entre amistad e intimidad.','¿Qué límite decide conservar o cruzar José?'],['La grieta de septiembre','Paz cuenta que está conociendo a otra persona. José descubre el costo de haber protegido durante años la máscara de amigo.','¿José rompe el silencio o protege la amistad?'],['Los siete dígitos','Paz entrega a José el número de la red fija de su casa y le pide que no pierdan la comunicación.','¿Qué significa para José ese pequeño papel?'],['La geometría del desvelo','En el reencuentro del año 2000, la distancia está llena de recuerdos que los demás no pueden leer.','¿José continúa hablando mediante señales o decide ser claro?'],['La llamada de 2001','José encuentra el papel, llama a la casa y ambos vuelven a encontrarse.','¿Qué busca realmente José al volver a llamar?'],['La pregunta difícil','Una conversación sobre responsabilidad obliga a ambos a imaginar un futuro que ninguno había pronunciado.','¿Desde qué lugar emocional responde José?'],['Cuando quiero que estés','Paz expresa la ausencia que más le duele: cuando necesita que José esté, él no está.','¿Qué hace José con esa verdad?'],['Lo que todavía puede decirse','Después de los reencuentros y los silencios, ambos deben decidir si la memoria seguirá siendo escondite o conversación verdadera.','¿Qué verdad decide decir José antes de que sea demasiado tarde?']];
const blueprint={title:'El Lado B',limits:PLAN_B_LIMITS,interaction:'one-question-three-choices',branches:rows.map((row,index)=>{const id=`branch-${index+1}`;return{id,position:index+1,title:row[0],context:row[1],question:{id:`${id}-q`,text:row[2],choices:choices(id,['Conservar el límite y guardar silencio.','Decir lo necesario con honestidad.','Dar un paso y aceptar el riesgo.'])}}})};
let session=null;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(session));} function restore(){try{const item=JSON.parse(localStorage.getItem(STORAGE_KEY));return item?.blueprint?.interaction==='one-question-three-choices'?item:null}catch{return null}}
function renderBranch(){const branch=session.blueprint.branches[session.current];if(!branch)return renderClosure();$('chapterLabel').textContent=`RAMA ${branch.position} DE ${PLAN_B_LIMITS.branches}`;$('decisionTitle').textContent=branch.title;$('summary').textContent=branch.context;$('question').textContent=branch.question.text;$('progressLabel').textContent=`Rama ${branch.position} de ${PLAN_B_LIMITS.branches}`;$('progressBar').style.width=`${branch.position/PLAN_B_LIMITS.branches*100}%`;$('trajectoryCount').textContent=`${session.responses.length} decisiones`;$('choices').replaceChildren();branch.question.choices.forEach(choice=>{const button=document.createElement('button');button.type='button';button.className='choice';button.textContent=choice.text;button.onclick=()=>choose(branch,choice);$('choices').append(button)});$('choice-panel').classList.remove('hidden');$('development').classList.add('hidden')}
function choose(branch,choice){try{session=directorPlanB(session,{branchId:branch.id,questionId:branch.question.id,choiceId:choice.id});save();const latest=session.actions.at(-1);$('bridge').textContent=latest.bridge;$('pulseReading').textContent=latest.action;$('trajectoryCount').textContent=`${session.responses.length} decisiones`;$('choice-panel').classList.add('hidden');$('development').classList.remove('hidden');$('continueBtn').innerHTML=session.status==='completed'?'DESCUBRIR MI DESENLACE <span>→</span>':'SEGUIR LEYENDO <span>→</span>'}catch(error){alert(error.message)}}
function renderClosure(){const outcome=buildPlanBOutcome(session);$('closureTitle').textContent=`Tus ${outcome.responseCount} decisiones encontraron un camino.`;$('closureText').textContent=outcome.epilogue;$('closureCount').textContent=`${outcome.responseCount} decisiones`;$('reader').classList.add('hidden');$('closure').classList.remove('hidden')}
function renderCompleteStory(){const outcome=buildPlanBOutcome(session);$('storyBody').replaceChildren();outcome.sections.forEach(section=>{const article=document.createElement('article'),title=document.createElement('h3'),text=document.createElement('p');article.className='story-section';title.textContent=section.title;text.textContent=section.text;article.append(title,text);$('storyBody').append(article)});$('storyEpilogue').textContent=outcome.epilogue;$('closure').classList.add('hidden');$('completeStory').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function start(){session=restore()||createPlanBReaderSession(blueprint);$('intro').classList.add('hidden');$('reader').classList.remove('hidden');renderBranch()}
$('startBtn').onclick=start;$('continueBtn').onclick=()=>{if(session.status==='completed')return renderClosure();renderBranch();window.scrollTo({top:0,behavior:'smooth'})};$('readStoryBtn').onclick=renderCompleteStory;$('backClosureBtn').onclick=()=>{$('completeStory').classList.add('hidden');$('closure').classList.remove('hidden')};$('restartBtn').onclick=()=>{localStorage.removeItem(STORAGE_KEY);session=null;$('closure').classList.add('hidden');$('completeStory').classList.add('hidden');$('reader').classList.add('hidden');$('intro').classList.remove('hidden')};
